# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for MOGLabs CEM application.
Builds a single-directory Windows executable.
"""

import os
import sys

block_cipher = None

a = Analysis(
    ['__main__.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('logo.png', '.'),
        ('moglabs_ico.png', '.'),
        ('roller.png', '.'),
    ],
    hiddenimports=[
        'mogui',
        'mogui.mogui',
        'mogui.mogdevice',
        'mogui.mogdiscover',
        'mogui.discoverui',
        'mogui.mogcmd',
        'mogui.graphs',
        'mogui.DateAxisItem',
        'mogui.compat',
        'mogui.firmwareui',
        'mogui.fwupd',
        'mogui.netwnd',
        'mogui.updatecheck',
        'mogui.thorlabs_new',
        'cem',
        'cem.cem_main',
        'cem.style',
        'cem.logging_configs',
        'cem.core',
        'cem.core.device_config',
        'cem.core.parameters',
        'cem.core.gui_script_common',
        'cem.core.single_mode_finder',
        'cem.core.read_pd',
        'cem.server',
        'cem.server.socket_server',
        'cem.server.cmd_handler',
        'cem.server.device_cmds',
        'cem.server.general_cmds',
        'cem.threads',
        'cem.threads.fail_save',
        'cem.threads.data_refresher',
        'cem.threads.drift_monitor',
        'cem.gui',
        'cem.gui.ui_cem_app',
        'cem.gui.server_status',
        'cem.windows',
        'cem.windows.photodiode_viewer',
        'cem.windows.toggle_resonance',
        'cem.windows.scan_control',
        'cem.windows.mld_control',
        'cem.windows.drift_warning',
        'cem.windows.failsafe_warning',
        'cem.windows.parameters',
        'cem.devices',
        'cem.devices.high_finesse_wavemeter',
        'cem.devices.eagle_eye',
        'cem.utils',
        'cem.utils.conversions',
        'cem.utils.data_structures',
        'cem.utils.typing',
        'PySide2',
        'PySide2.QtCore',
        'PySide2.QtGui',
        'PySide2.QtWidgets',
        'numpy',
        'scipy',
        'scipy.signal',
        'scipy.optimize',
        'matplotlib',
        'pyqtgraph',
        'serial',
        'serial.tools',
        'serial.tools.list_ports',
        'psutil',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='CEM',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='moglabs_ico.png',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='CEM',
)
