# uncompyle6 version 3.9.3
# Python bytecode version base 3.8.0 (3413)
# Decompiled from: Python 3.9.6 (default, Apr 30 2025, 02:07:17) 
# [Clang 17.0.0 (clang-1700.0.13.5)]
# Embedded file name: cem\gui\ui_cem_app.py
try:
    from PySide2.QtCore import *
    from PySide2.QtGui import *
    from PySide2.QtWidgets import *
except ImportError:
    from PySide6.QtCore import *
    from PySide6.QtGui import *
    from PySide6.QtWidgets import *

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1280, 720))
        icon = QIcon()
        icon.addFile("../mogui/moglabsbig.ico", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.Australia))
        self.actionLoad_configuration = QAction(MainWindow)
        self.actionLoad_configuration.setObjectName("actionLoad_configuration")
        self.actionSave_configuration_file = QAction(MainWindow)
        self.actionSave_configuration_file.setObjectName("actionSave_configuration_file")
        self.actionReset = QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionConnectCEM = QAction(MainWindow)
        self.actionConnectCEM.setObjectName("actionConnectCEM")
        self.actionConnectMLD = QAction(MainWindow)
        self.actionConnectMLD.setObjectName("actionConnectMLD")
        self.actionConnectFZW = QAction(MainWindow)
        self.actionConnectFZW.setObjectName("actionConnectFZW")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionCEMcmd = QAction(MainWindow)
        self.actionCEMcmd.setObjectName("actionCEMcmd")
        self.actionMLDcmd = QAction(MainWindow)
        self.actionMLDcmd.setObjectName("actionMLDcmd")
        self.actionFZWcmd = QAction(MainWindow)
        self.actionFZWcmd.setObjectName("actionFZWcmd")
        self.actionOpenOnlineManual = QAction(MainWindow)
        self.actionOpenOnlineManual.setObjectName("actionOpenOnlineManual")
        self.actionMLDSettings = QAction(MainWindow)
        self.actionMLDSettings.setObjectName("actionMLDSettings")
        self.actionScan_control = QAction(MainWindow)
        self.actionScan_control.setObjectName("actionScan_control")
        self.actionReset_CEM_server = QAction(MainWindow)
        self.actionReset_CEM_server.setObjectName("actionReset_CEM_server")
        self.actionParameters = QAction(MainWindow)
        self.actionParameters.setObjectName("actionParameters")
        self.actionHigh_Finesse_Wavemeter_HFW = QAction(MainWindow)
        self.actionHigh_Finesse_Wavemeter_HFW.setObjectName("actionHigh_Finesse_Wavemeter_HFW")
        self.actionConnectHFW = QAction(MainWindow)
        self.actionConnectHFW.setObjectName("actionConnectHFW")
        self.actionHideHFWApp = QAction(MainWindow)
        self.actionHideHFWApp.setObjectName("actionHideHFWApp")
        self.actionShowHFWApp = QAction(MainWindow)
        self.actionShowHFWApp.setObjectName("actionShowHFWApp")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        font = QFont()
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("")
        self.verticalLayout_10 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, -1, 0, 0)
        self.MainTabWidget = QTabWidget(self.centralwidget)
        self.MainTabWidget.setObjectName("MainTabWidget")
        self.MainTabWidget.setFont(font)
        self.MainTabWidget.setAutoFillBackground(False)
        self.MainTabWidget.setTabPosition(QTabWidget.North)
        self.MainTabWidget.setTabShape(QTabWidget.Rounded)
        self.MainTabWidget.setDocumentMode(False)
        self.MainTabWidget.setTabsClosable(False)
        self.MainTabWidget.setMovable(False)
        self.MainTabWidget.setTabBarAutoHide(False)
        self.tab_manual = QWidget()
        self.tab_manual.setObjectName("tab_manual")
        self.tab_manual.setFont(font)
        self.verticalLayout = QVBoxLayout(self.tab_manual)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_manual = QHBoxLayout()
        self.horizontalLayout_manual.setObjectName("horizontalLayout_manual")
        self.manual_left_coulmn = QFrame(self.tab_manual)
        self.manual_left_coulmn.setObjectName("manual_left_coulmn")
        self.manual_left_coulmn.setMinimumSize(QSize(291, 0))
        self.manual_left_coulmn.setMaximumSize(QSize(291, 16777215))
        self.manual_left_coulmn.setFont(font)
        self.manual_left_coulmn.setFrameShape(QFrame.NoFrame)
        self.manual_left_coulmn.setFrameShadow(QFrame.Plain)
        self.manual_left_coulmn.setLineWidth(0)
        self.verticalLayout_9 = QVBoxLayout(self.manual_left_coulmn)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.manual_settings = QFrame(self.manual_left_coulmn)
        self.manual_settings.setObjectName("manual_settings")
        self.manual_settings.setFont(font)
        self.manual_settings.setFrameShape(QFrame.NoFrame)
        self.manual_settings.setFrameShadow(QFrame.Plain)
        self.manual_settings.setLineWidth(0)
        self.manual_laser_settings = QGroupBox(self.manual_settings)
        self.manual_laser_settings.setObjectName("manual_laser_settings")
        self.manual_laser_settings.setGeometry(QRect(10, 10, 271, 151))
        self.manual_laser_settings.setFont(font)
        self.frame_current = QFrame(self.manual_laser_settings)
        self.frame_current.setObjectName("frame_current")
        self.frame_current.setGeometry(QRect(10, 30, 251, 31))
        self.frame_current.setFont(font)
        self.frame_current.setFrameShape(QFrame.StyledPanel)
        self.frame_current.setFrameShadow(QFrame.Raised)
        self.label_laser_current = QLabel(self.frame_current)
        self.label_laser_current.setObjectName("label_laser_current")
        self.label_laser_current.setGeometry(QRect(0, 0, 71, 31))
        self.label_laser_current.setFont(font)
        self.btn_current_on_off = QPushButton(self.frame_current)
        self.btn_current_on_off.setObjectName("btn_current_on_off")
        self.btn_current_on_off.setGeometry(QRect(190, 0, 61, 31))
        self.laser_current = QLabel(self.frame_current)
        self.laser_current.setObjectName("laser_current")
        self.laser_current.setGeometry(QRect(80, 0, 101, 31))
        self.laser_current.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.frame_temperature = QFrame(self.manual_laser_settings)
        self.frame_temperature.setObjectName("frame_temperature")
        self.frame_temperature.setGeometry(QRect(10, 70, 251, 31))
        self.frame_temperature.setFont(font)
        self.frame_temperature.setFrameShape(QFrame.StyledPanel)
        self.frame_temperature.setFrameShadow(QFrame.Raised)
        self.label_laser_temperature = QLabel(self.frame_temperature)
        self.label_laser_temperature.setObjectName("label_laser_temperature")
        self.label_laser_temperature.setGeometry(QRect(0, 0, 101, 31))
        self.label_laser_temperature.setFont(font)
        self.btn_tec_on_off = QPushButton(self.frame_temperature)
        self.btn_tec_on_off.setObjectName("btn_tec_on_off")
        self.btn_tec_on_off.setGeometry(QRect(190, 0, 61, 31))
        self.laser_temperature = QLabel(self.frame_temperature)
        self.laser_temperature.setObjectName("laser_temperature")
        self.laser_temperature.setGeometry(QRect(106, 0, 71, 31))
        self.laser_temperature.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.frame_filter_position = QFrame(self.manual_laser_settings)
        self.frame_filter_position.setObjectName("frame_filter_position")
        self.frame_filter_position.setGeometry(QRect(10, 110, 251, 31))
        self.frame_filter_position.setFont(font)
        self.frame_filter_position.setFrameShape(QFrame.StyledPanel)
        self.frame_filter_position.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame_filter_position)
        self.label.setObjectName("label")
        self.label.setGeometry(QRect(0, 0, 101, 31))
        self.label.setFont(font)
        self.btn_home_filter = QPushButton(self.frame_filter_position)
        self.btn_home_filter.setObjectName("btn_home_filter")
        self.btn_home_filter.setGeometry(QRect(190, 0, 61, 31))
        self.filter_angle = QLabel(self.frame_filter_position)
        self.filter_angle.setObjectName("filter_angle")
        self.filter_angle.setGeometry(QRect(106, 0, 71, 31))
        self.filter_angle.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.manual_frequency_settings = QGroupBox(self.manual_settings)
        self.manual_frequency_settings.setObjectName("manual_frequency_settings")
        self.manual_frequency_settings.setGeometry(QRect(10, 170, 271, 351))
        self.manual_frequency_settings.setFont(font)
        self.frame_frequency_error = QFrame(self.manual_frequency_settings)
        self.frame_frequency_error.setObjectName("frame_frequency_error")
        self.frame_frequency_error.setGeometry(QRect(10, 180, 251, 51))
        self.frame_frequency_error.setFrameShape(QFrame.StyledPanel)
        self.frame_frequency_error.setFrameShadow(QFrame.Raised)
        self.frequency_error = QLabel(self.frame_frequency_error)
        self.frequency_error.setObjectName("frequency_error")
        self.frequency_error.setGeometry(QRect(0, 20, 211, 31))
        font1 = QFont()
        font1.setPointSize(20)
        self.frequency_error.setFont(font1)
        self.frequency_error.setAlignment(Qt.AlignRight | Qt.AlignTrailing | Qt.AlignVCenter)
        self.label_frequency_error = QLabel(self.frame_frequency_error)
        self.label_frequency_error.setObjectName("label_frequency_error")
        self.label_frequency_error.setGeometry(QRect(0, 0, 151, 21))
        self.label_frequency_error.setFont(font)
        self.frame_mode_and_mode = QFrame(self.manual_frequency_settings)
        self.frame_mode_and_mode.setObjectName("frame_mode_and_mode")
        self.frame_mode_and_mode.setGeometry(QRect(9, 240, 261, 111))
        self.frame_mode_and_mode.setFrameShape(QFrame.StyledPanel)
        self.frame_mode_and_mode.setFrameShadow(QFrame.Raised)
        self.mode = QComboBox(self.frame_mode_and_mode)
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.addItem("")
        self.mode.setObjectName("mode")
        self.mode.setGeometry(QRect(110, 0, 151, 31))
        self.mode.setFont(font)
        self.mode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_mode = QLabel(self.frame_mode_and_mode)
        self.label_mode.setObjectName("label_mode")
        self.label_mode.setGeometry(QRect(0, 0, 51, 31))
        self.label_mode.setFont(font)
        self.btn_move_to_frequency = QPushButton(self.frame_mode_and_mode)
        self.btn_move_to_frequency.setObjectName("btn_move_to_frequency")
        self.btn_move_to_frequency.setGeometry(QRect(0, 80, 101, 31))
        self.btn_move_to_frequency.setFont(font)
        self.btn_move_to_frequency.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.btn_move_and_hold = QPushButton(self.frame_mode_and_mode)
        self.btn_move_and_hold.setObjectName("btn_move_and_hold")
        self.btn_move_and_hold.setGeometry(QRect(110, 80, 151, 31))
        self.label_retry_on_error = QLabel(self.frame_mode_and_mode)
        self.label_retry_on_error.setObjectName("label_retry_on_error")
        self.label_retry_on_error.setGeometry(QRect(0, 40, 111, 31))
        self.label_retry_on_error.setFont(font)
        self.retry_on_error = QSpinBox(self.frame_mode_and_mode)
        self.retry_on_error.setObjectName("retry_on_error")
        self.retry_on_error.setGeometry(QRect(110, 40, 151, 31))
        self.retry_on_error.setValue(1)
        self.frame = QFrame(self.manual_frequency_settings)
        self.frame.setObjectName("frame")
        self.frame.setGeometry(QRect(10, 30, 251, 141))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_set_frequency = QLabel(self.frame)
        self.label_set_frequency.setObjectName("label_set_frequency")
        self.label_set_frequency.setGeometry(QRect(0, 0, 191, 31))
        self.label_set_frequency.setFont(font)
        self.set_frequency = QDoubleSpinBox(self.frame)
        self.set_frequency.setObjectName("set_frequency")
        self.set_frequency.setGeometry(QRect(0, 30, 251, 41))
        self.set_frequency.setFont(font1)
        self.set_frequency.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.set_frequency.setDecimals(6)
        self.set_frequency.setMinimum(100.0)
        self.set_frequency.setMaximum(999.0)
        self.set_frequency.setValue(385.0)
        self.label_set_wavelength = QLabel(self.frame)
        self.label_set_wavelength.setObjectName("label_set_wavelength")
        self.label_set_wavelength.setGeometry(QRect(0, 70, 191, 31))
        self.label_set_wavelength.setFont(font)
        self.set_wavelength = QDoubleSpinBox(self.frame)
        self.set_wavelength.setObjectName("set_wavelength")
        self.set_wavelength.setGeometry(QRect(0, 100, 251, 41))
        self.set_wavelength.setFont(font1)
        self.set_wavelength.setAlignment(Qt.AlignLeading | Qt.AlignLeft | Qt.AlignVCenter)
        self.set_wavelength.setDecimals(6)
        self.set_wavelength.setMinimum(100.0)
        self.set_wavelength.setMaximum(999.0)
        self.set_wavelength.setValue(778.681709)
        self.verticalLayout_9.addWidget(self.manual_settings)
        self.horizontalLayout_manual.addWidget(self.manual_left_coulmn)
        self.manual_right_coulmn = QFrame(self.tab_manual)
        self.manual_right_coulmn.setObjectName("manual_right_coulmn")
        self.manual_right_coulmn.setFrameShape(QFrame.NoFrame)
        self.manual_right_coulmn.setFrameShadow(QFrame.Plain)
        self.manual_right_coulmn.setLineWidth(0)
        self.verticalLayout_8 = QVBoxLayout(self.manual_right_coulmn)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_8.setContentsMargins(0, 18, 0, 0)
        self.manual_tabWidget = QTabWidget(self.manual_right_coulmn)
        self.manual_tabWidget.setObjectName("manual_tabWidget")
        self.manual_tabWidget.setFont(font)
        self.manual_tabWidget.setAutoFillBackground(False)
        self.manual_tabWidget.setDocumentMode(False)
        self.manual_tabWidget.setTabBarAutoHide(False)
        self.tab_filter_position = QWidget()
        self.tab_filter_position.setObjectName("tab_filter_position")
        self.verticalLayout_4 = QVBoxLayout(self.tab_filter_position)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.manual_filter_position_graph = QVBoxLayout()
        self.manual_filter_position_graph.setObjectName("manual_filter_position_graph")
        self.manual_filter_position_graph.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.manual_filter_position_graph.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_4.addLayout(self.manual_filter_position_graph)
        self.manual_tabWidget.addTab(self.tab_filter_position, "")
        self.tab_mode_scans = QWidget()
        self.tab_mode_scans.setObjectName("tab_mode_scans")
        self.verticalLayout_7 = QVBoxLayout(self.tab_mode_scans)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_mode_scan_buttons = QFrame(self.tab_mode_scans)
        self.frame_mode_scan_buttons.setObjectName("frame_mode_scan_buttons")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frame_mode_scan_buttons.sizePolicy().hasHeightForWidth())
        self.frame_mode_scan_buttons.setSizePolicy(sizePolicy1)
        self.frame_mode_scan_buttons.setMinimumSize(QSize(0, 40))
        self.frame_mode_scan_buttons.setMaximumSize(QSize(16777215, 40))
        self.manual_mode_scan_buttons = QHBoxLayout(self.frame_mode_scan_buttons)
        self.manual_mode_scan_buttons.setSpacing(6)
        self.manual_mode_scan_buttons.setObjectName("manual_mode_scan_buttons")
        self.manual_mode_scan_buttons.setContentsMargins(0, 0, 0, 0)
        self.btn_mode_scan = QPushButton(self.frame_mode_scan_buttons)
        self.btn_mode_scan.setObjectName("btn_mode_scan")
        self.btn_mode_scan.setMinimumSize(QSize(0, 27))
        self.btn_mode_scan.setFont(font)
        self.manual_mode_scan_buttons.addWidget(self.btn_mode_scan)
        self.btn_mode_scan_and_move = QPushButton(self.frame_mode_scan_buttons)
        self.btn_mode_scan_and_move.setObjectName("btn_mode_scan_and_move")
        self.btn_mode_scan_and_move.setMinimumSize(QSize(0, 27))
        self.btn_mode_scan_and_move.setFont(font)
        self.manual_mode_scan_buttons.addWidget(self.btn_mode_scan_and_move)
        self.btn_mode_scan_resume = QPushButton(self.frame_mode_scan_buttons)
        self.btn_mode_scan_resume.setObjectName("btn_mode_scan_resume")
        self.btn_mode_scan_resume.setMinimumSize(QSize(0, 27))
        self.btn_mode_scan_resume.setFont(font)
        self.manual_mode_scan_buttons.addWidget(self.btn_mode_scan_resume)
        self.verticalLayout_7.addWidget(self.frame_mode_scan_buttons)
        self.manual_mode_scan_graph = QVBoxLayout()
        self.manual_mode_scan_graph.setObjectName("manual_mode_scan_graph")
        self.manual_mode_scan_graph.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_7.addLayout(self.manual_mode_scan_graph)
        self.manual_tabWidget.addTab(self.tab_mode_scans, "")
        self.tab_time_series = QWidget()
        self.tab_time_series.setObjectName("tab_time_series")
        self.verticalLayout_6 = QVBoxLayout(self.tab_time_series)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_time_series_buttons = QFrame(self.tab_time_series)
        self.frame_time_series_buttons.setObjectName("frame_time_series_buttons")
        sizePolicy1.setHeightForWidth(self.frame_time_series_buttons.sizePolicy().hasHeightForWidth())
        self.frame_time_series_buttons.setSizePolicy(sizePolicy1)
        self.frame_time_series_buttons.setMinimumSize(QSize(0, 31))
        self.frame_time_series_buttons.setMaximumSize(QSize(16777215, 31))
        self.verticalLayout_3 = QVBoxLayout(self.frame_time_series_buttons)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.btn_clear_log = QPushButton(self.frame_time_series_buttons)
        self.btn_clear_log.setObjectName("btn_clear_log")
        self.btn_clear_log.setMinimumSize(QSize(0, 27))
        self.btn_clear_log.setFont(font)
        self.verticalLayout_3.addWidget(self.btn_clear_log)
        self.verticalLayout_6.addWidget(self.frame_time_series_buttons)
        self.manual_time_series_graph = QVBoxLayout()
        self.manual_time_series_graph.setObjectName("manual_time_series_graph")
        self.manual_time_series_graph.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_6.addLayout(self.manual_time_series_graph)
        self.manual_tabWidget.addTab(self.tab_time_series, "")
        self.manual_fzw = QWidget()
        self.manual_fzw.setObjectName("manual_fzw")
        self.verticalLayout_5 = QVBoxLayout(self.manual_fzw)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.manual_fzw_graph = QVBoxLayout()
        self.manual_fzw_graph.setObjectName("manual_fzw_graph")
        self.verticalLayout_5.addLayout(self.manual_fzw_graph)
        self.manual_tabWidget.addTab(self.manual_fzw, "")
        self.verticalLayout_8.addWidget(self.manual_tabWidget)
        self.horizontalLayout_manual.addWidget(self.manual_right_coulmn)
        self.verticalLayout.addLayout(self.horizontalLayout_manual)
        self.MainTabWidget.addTab(self.tab_manual, "")
        self.tab_resonance = QWidget()
        self.tab_resonance.setObjectName("tab_resonance")
        self.verticalLayout_r1 = QVBoxLayout(self.tab_resonance)
        self.verticalLayout_r1.setSpacing(0)
        self.verticalLayout_r1.setObjectName("verticalLayout_r1")
        self.verticalLayout_r1.setContentsMargins(0, 0, 0, 0)
        self.tab_spectroscopy = QWidget()
        self.tab_spectroscopy.setObjectName("tab_spectroscopy")
        self.verticalLayout_11 = QVBoxLayout(self.tab_spectroscopy)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_spectroscopy = QHBoxLayout()
        self.horizontalLayout_spectroscopy.setObjectName("horizontalLayout_spectroscopy")
        self.spectroscopy_left_coulmn = QFrame(self.tab_spectroscopy)
        self.spectroscopy_left_coulmn.setObjectName("spectroscopy_left_coulmn")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.spectroscopy_left_coulmn.sizePolicy().hasHeightForWidth())
        self.spectroscopy_left_coulmn.setSizePolicy(sizePolicy2)
        self.spectroscopy_left_coulmn.setMinimumSize(QSize(291, 281))
        self.spectroscopy_left_coulmn.setMaximumSize(QSize(291, 16777215))
        self.spectroscopy_left_coulmn.setFrameShape(QFrame.NoFrame)
        self.spectroscopy_left_coulmn.setFrameShadow(QFrame.Plain)
        self.spectroscopy_left_coulmn.setLineWidth(0)
        self.verticalLayout_12 = QVBoxLayout(self.spectroscopy_left_coulmn)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.spectroscopy_settings = QFrame(self.spectroscopy_left_coulmn)
        self.spectroscopy_settings.setObjectName("spectroscopy_settings")
        self.spectroscopy_settings.setFrameShape(QFrame.StyledPanel)
        self.spectroscopy_settings.setFrameShadow(QFrame.Raised)
        self.spectroscopy_laser_settings = QGroupBox(self.spectroscopy_settings)
        self.spectroscopy_laser_settings.setObjectName("spectroscopy_laser_settings")
        self.spectroscopy_laser_settings.setGeometry(QRect(10, 10, 271, 511))
        sizePolicy3 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.spectroscopy_laser_settings.sizePolicy().hasHeightForWidth())
        self.spectroscopy_laser_settings.setSizePolicy(sizePolicy3)
        self.spectroscopy_laser_settings.setMinimumSize(QSize(271, 511))
        self.spectroscopy_laser_settings.setMaximumSize(QSize(271, 511))
        self.spectroscopy_laser_settings.setFont(font)
        self.btn_spectroscopy_start = QPushButton(self.spectroscopy_laser_settings)
        self.btn_spectroscopy_start.setObjectName("btn_spectroscopy_start")
        self.btn_spectroscopy_start.setGeometry(QRect(10, 390, 251, 51))
        self.btn_spectroscopy_start.setFont(font1)
        self.btn_spectroscopy_start.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.frame_scan_status = QFrame(self.spectroscopy_laser_settings)
        self.frame_scan_status.setObjectName("frame_scan_status")
        self.frame_scan_status.setGeometry(QRect(9, 290, 261, 81))
        self.frame_scan_status.setFrameShape(QFrame.StyledPanel)
        self.frame_scan_status.setFrameShadow(QFrame.Raised)
        self.label_scan_speed = QLabel(self.frame_scan_status)
        self.label_scan_speed.setObjectName("label_scan_speed")
        self.label_scan_speed.setGeometry(QRect(0, 25, 91, 31))
        self.label_scan_speed.setFont(font)
        self.label_sample_rate = QLabel(self.frame_scan_status)
        self.label_sample_rate.setObjectName("label_sample_rate")
        self.label_sample_rate.setGeometry(QRect(0, 50, 91, 31))
        self.label_sample_rate.setFont(font)
        self.label_scan_status = QLabel(self.frame_scan_status)
        self.label_scan_status.setObjectName("label_scan_status")
        self.label_scan_status.setGeometry(QRect(0, 0, 91, 31))
        self.label_scan_status.setFont(font)
        self.scan_status = QLabel(self.frame_scan_status)
        self.scan_status.setObjectName("scan_status")
        self.scan_status.setGeometry(QRect(100, 0, 161, 31))
        self.scan_status.setFont(font)
        self.scan_speed = QLabel(self.frame_scan_status)
        self.scan_speed.setObjectName("scan_speed")
        self.scan_speed.setGeometry(QRect(100, 25, 161, 31))
        self.scan_speed.setFont(font)
        self.sample_rate = QLabel(self.frame_scan_status)
        self.sample_rate.setObjectName("sample_rate")
        self.sample_rate.setGeometry(QRect(100, 50, 161, 31))
        self.sample_rate.setFont(font)
        self.frame_scan_settings = QFrame(self.spectroscopy_laser_settings)
        self.frame_scan_settings.setObjectName("frame_scan_settings")
        self.frame_scan_settings.setGeometry(QRect(10, 180, 251, 101))
        self.frame_scan_settings.setFrameShape(QFrame.StyledPanel)
        self.frame_scan_settings.setFrameShadow(QFrame.Raised)
        self.spectroscopy_scan_mode = QComboBox(self.frame_scan_settings)
        self.spectroscopy_scan_mode.addItem("")
        self.spectroscopy_scan_mode.addItem("")
        self.spectroscopy_scan_mode.addItem("")
        self.spectroscopy_scan_mode.setObjectName("spectroscopy_scan_mode")
        self.spectroscopy_scan_mode.setGeometry(QRect(100, 35, 151, 31))
        self.spectroscopy_scan_mode.setFont(font)
        self.spectroscopy_scan_mode.setAutoFillBackground(False)
        self.spectroscopy_scan_mode.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_scan_mode = QLabel(self.frame_scan_settings)
        self.label_scan_mode.setObjectName("label_scan_mode")
        self.label_scan_mode.setGeometry(QRect(0, 35, 91, 31))
        self.label_scan_mode.setFont(font)
        self.label_scan_replicates = QLabel(self.frame_scan_settings)
        self.label_scan_replicates.setObjectName("label_scan_replicates")
        self.label_scan_replicates.setGeometry(QRect(0, 0, 81, 31))
        self.label_scan_replicates.setFont(font)
        self.scan_replicates = QSpinBox(self.frame_scan_settings)
        self.scan_replicates.setObjectName("scan_replicates")
        self.scan_replicates.setGeometry(QRect(100, 0, 151, 31))
        self.scan_replicates.setMinimum(1)
        self.scan_replicates.setValue(2)
        self.label_sample_rate_2 = QLabel(self.frame_scan_settings)
        self.label_sample_rate_2.setObjectName("label_sample_rate_2")
        self.label_sample_rate_2.setGeometry(QRect(0, 70, 91, 31))
        self.label_sample_rate_2.setFont(font)
        self.spectroscopy_sample_rate = QComboBox(self.frame_scan_settings)
        self.spectroscopy_sample_rate.addItem("")
        self.spectroscopy_sample_rate.addItem("")
        self.spectroscopy_sample_rate.setObjectName("spectroscopy_sample_rate")
        self.spectroscopy_sample_rate.setGeometry(QRect(100, 70, 151, 31))
        self.spectroscopy_sample_rate.setFont(font)
        self.spectroscopy_sample_rate.setAutoFillBackground(False)
        self.spectroscopy_sample_rate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_set_frequencies = QFrame(self.spectroscopy_laser_settings)
        self.frame_set_frequencies.setObjectName("frame_set_frequencies")
        self.frame_set_frequencies.setGeometry(QRect(10, 30, 251, 141))
        self.frame_set_frequencies.setFrameShape(QFrame.StyledPanel)
        self.frame_set_frequencies.setFrameShadow(QFrame.Raised)
        self.max_frequency = QDoubleSpinBox(self.frame_set_frequencies)
        self.max_frequency.setObjectName("max_frequency")
        self.max_frequency.setGeometry(QRect(0, 100, 251, 41))
        self.max_frequency.setFont(font1)
        self.max_frequency.setDecimals(6)
        self.max_frequency.setMinimum(100.0)
        self.max_frequency.setMaximum(999.0)
        self.max_frequency.setValue(384.2425)
        self.min_frequency = QDoubleSpinBox(self.frame_set_frequencies)
        self.min_frequency.setObjectName("min_frequency")
        self.min_frequency.setGeometry(QRect(0, 30, 251, 41))
        self.min_frequency.setFont(font1)
        self.min_frequency.setDecimals(6)
        self.min_frequency.setMinimum(100.0)
        self.min_frequency.setMaximum(999.0)
        self.min_frequency.setValue(384.225)
        self.label_min_frequency = QLabel(self.frame_set_frequencies)
        self.label_min_frequency.setObjectName("label_min_frequency")
        self.label_min_frequency.setGeometry(QRect(0, 0, 171, 31))
        self.label_min_frequency.setFont(font)
        self.label_max_frequency = QLabel(self.frame_set_frequencies)
        self.label_max_frequency.setObjectName("label_max_frequency")
        self.label_max_frequency.setGeometry(QRect(0, 70, 171, 31))
        self.label_max_frequency.setFont(font)
        self.btn_scan_n_peaks = QPushButton(self.spectroscopy_laser_settings)
        self.btn_scan_n_peaks.setObjectName("btn_scan_n_peaks")
        self.btn_scan_n_peaks.setGeometry(QRect(10, 450, 121, 51))
        self.btn_toggle_resonance = QPushButton(self.spectroscopy_laser_settings)
        self.btn_toggle_resonance.setObjectName("btn_toggle_resonance")
        self.btn_toggle_resonance.setGeometry(QRect(140, 450, 121, 51))
        self.verticalLayout_12.addWidget(self.spectroscopy_settings)
        self.horizontalLayout_spectroscopy.addWidget(self.spectroscopy_left_coulmn)
        self.spectroscopy_right_coulmn = QFrame(self.tab_spectroscopy)
        self.spectroscopy_right_coulmn.setObjectName("spectroscopy_right_coulmn")
        self.spectroscopy_right_coulmn.setFrameShape(QFrame.StyledPanel)
        self.spectroscopy_right_coulmn.setFrameShadow(QFrame.Raised)
        self.verticalLayout_14 = QVBoxLayout(self.spectroscopy_right_coulmn)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_spectroscopy_buttons = QFrame(self.spectroscopy_right_coulmn)
        self.frame_spectroscopy_buttons.setObjectName("frame_spectroscopy_buttons")
        sizePolicy1.setHeightForWidth(self.frame_spectroscopy_buttons.sizePolicy().hasHeightForWidth())
        self.frame_spectroscopy_buttons.setSizePolicy(sizePolicy1)
        self.frame_spectroscopy_buttons.setMinimumSize(QSize(0, 31))
        self.frame_spectroscopy_buttons.setMaximumSize(QSize(16777215, 31))
        self.frame_spectroscopy_buttons.setFrameShape(QFrame.StyledPanel)
        self.frame_spectroscopy_buttons.setFrameShadow(QFrame.Raised)
        self.verticalLayout_13 = QVBoxLayout(self.frame_spectroscopy_buttons)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.btn_clear_spectroscopy = QPushButton(self.frame_spectroscopy_buttons)
        self.btn_clear_spectroscopy.setObjectName("btn_clear_spectroscopy")
        self.btn_clear_spectroscopy.setMinimumSize(QSize(0, 27))
        self.btn_clear_spectroscopy.setFont(font)
        self.verticalLayout_13.addWidget(self.btn_clear_spectroscopy)
        self.verticalLayout_14.addWidget(self.frame_spectroscopy_buttons)
        self.spectroscopy_graph = QVBoxLayout()
        self.spectroscopy_graph.setObjectName("spectroscopy_graph")
        self.verticalLayout_14.addLayout(self.spectroscopy_graph)
        self.horizontalLayout_spectroscopy.addWidget(self.spectroscopy_right_coulmn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_spectroscopy)
        self.MainTabWidget.addTab(self.tab_resonance, "")
        self.verticalLayout_10.addWidget(self.MainTabWidget)
        self.frame_bottom = QFrame(self.centralwidget)
        self.frame_bottom.setObjectName("frame_bottom")
        self.frame_bottom.setMinimumSize(QSize(0, 100))
        self.frame_bottom.setMaximumSize(QSize(16777215, 100))
        self.frame_bottom.setAutoFillBackground(False)
        self.frame_bottom.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_bottom.setFrameShape(QFrame.StyledPanel)
        self.frame_bottom.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame_bottom)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.frame_bottom_left = QFrame(self.frame_bottom)
        self.frame_bottom_left.setObjectName("frame_bottom_left")
        sizePolicy3.setHeightForWidth(self.frame_bottom_left.sizePolicy().hasHeightForWidth())
        self.frame_bottom_left.setSizePolicy(sizePolicy3)
        self.frame_bottom_left.setMinimumSize(QSize(291, 100))
        self.frame_bottom_left.setMaximumSize(QSize(291, 100))
        self.frame_bottom_left.setFrameShape(QFrame.StyledPanel)
        self.frame_bottom_left.setFrameShadow(QFrame.Raised)
        self.verticalLayout_2 = QVBoxLayout(self.frame_bottom_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.manual_progressBar = QProgressBar(self.frame_bottom_left)
        self.manual_progressBar.setObjectName("manual_progressBar")
        self.manual_progressBar.setValue(0)
        self.manual_progressBar.setTextVisible(False)
        self.verticalLayout_2.addWidget(self.manual_progressBar)
        self.btn_abort = QPushButton(self.frame_bottom_left)
        self.btn_abort.setObjectName("btn_abort")
        self.btn_abort.setEnabled(True)
        self.btn_abort.setFont(font1)
        self.btn_abort.setStyleSheet("background-color: rgb(255, 0, 0);\ncolor: rgb(255, 255, 255);")
        self.verticalLayout_2.addWidget(self.btn_abort)
        self.horizontalLayout_2.addWidget(self.frame_bottom_left)
        self.frame_2 = QFrame(self.frame_bottom)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_measured_frequency = QFrame(self.frame_bottom)
        self.frame_measured_frequency.setObjectName("frame_measured_frequency")
        self.frame_measured_frequency.setMinimumSize(QSize(801, 100))
        self.frame_measured_frequency.setMaximumSize(QSize(801, 100))
        self.frame_measured_frequency.setFrameShape(QFrame.NoFrame)
        self.frame_measured_frequency.setFrameShadow(QFrame.Plain)
        self.horizontalLayout_3 = QHBoxLayout(self.frame_measured_frequency)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.frame_measured_frequency_2 = QFrame(self.frame_measured_frequency)
        self.frame_measured_frequency_2.setObjectName("frame_measured_frequency_2")
        self.frame_measured_frequency_2.setMinimumSize(QSize(0, 100))
        self.frame_measured_frequency_2.setMaximumSize(QSize(16777215, 100))
        self.frame_measured_frequency_2.setFrameShape(QFrame.StyledPanel)
        self.frame_measured_frequency_2.setFrameShadow(QFrame.Raised)
        self.verticalLayout_15 = QVBoxLayout(self.frame_measured_frequency_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(-1, -1, 9, -1)
        self.measured_frequency = QPushButton(self.frame_measured_frequency_2)
        self.measured_frequency.setObjectName("measured_frequency")
        self.measured_frequency.setMinimumSize(QSize(0, 80))
        self.measured_frequency.setMaximumSize(QSize(16777215, 80))
        font2 = QFont()
        font2.setPointSize(64)
        font2.setBold(True)
        font2.setWeight(15)
        self.measured_frequency.setFont(font2)
        self.measured_frequency.setFlat(True)
        self.verticalLayout_15.addWidget(self.measured_frequency)
        self.horizontalLayout_3.addWidget(self.frame_measured_frequency_2)
        self.display_unit = QComboBox(self.frame_measured_frequency)
        self.display_unit.addItem("")
        self.display_unit.addItem("")
        self.display_unit.addItem("")
        self.display_unit.addItem("")
        self.display_unit.setObjectName("display_unit")
        self.display_unit.setMinimumSize(QSize(221, 61))
        self.display_unit.setMaximumSize(QSize(221, 61))
        font3 = QFont()
        font3.setPointSize(32)
        font3.setBold(True)
        font3.setWeight(75)
        self.display_unit.setFont(font3)
        self.display_unit.setFocusPolicy(Qt.NoFocus)
        self.display_unit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout_3.addWidget(self.display_unit)
        self.horizontalLayout_2.addWidget(self.frame_measured_frequency)
        self.bottom_right_frame = QFrame(self.frame_bottom)
        self.bottom_right_frame.setObjectName("bottom_right_frame")
        self.bottom_right_frame.setMinimumSize(QSize(0, 0))
        self.bottom_right_frame.setMaximumSize(QSize(16777215, 16777215))
        self.bottom_right_frame.setFont(font)
        self.bottom_right_frame.setFrameShape(QFrame.StyledPanel)
        self.bottom_right_frame.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_4 = QHBoxLayout(self.bottom_right_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_2.addWidget(self.bottom_right_frame)
        self.verticalLayout_10.addWidget(self.frame_bottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName("menubar")
        self.menubar.setGeometry(QRect(0, 0, 1280, 21))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFile.setStyleSheet("default")
        self.menuDevices = QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuConnect = QMenu(self.menuDevices)
        self.menuConnect.setObjectName("menuConnect")
        self.menuAdvanced_settings = QMenu(self.menuDevices)
        self.menuAdvanced_settings.setObjectName("menuAdvanced_settings")
        self.menuHFW_application_visibility = QMenu(self.menuAdvanced_settings)
        self.menuHFW_application_visibility.setObjectName("menuHFW_application_visibility")
        self.menuDebug = QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        self.menuCommander = QMenu(self.menuDebug)
        self.menuCommander.setObjectName("menuCommander")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuScans = QMenu(self.menubar)
        self.menuScans.setObjectName("menuScans")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuScans.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionClose)
        self.menuDevices.addAction(self.menuConnect.menuAction())
        self.menuDevices.addAction(self.menuAdvanced_settings.menuAction())
        self.menuConnect.addAction(self.actionConnectCEM)
        self.menuConnect.addAction(self.actionConnectMLD)
        self.menuConnect.addAction(self.actionConnectFZW)
        self.menuConnect.addAction(self.actionConnectHFW)
        self.menuAdvanced_settings.addAction(self.actionMLDSettings)
        self.menuAdvanced_settings.addAction(self.actionParameters)
        self.menuAdvanced_settings.addAction(self.menuHFW_application_visibility.menuAction())
        self.menuHFW_application_visibility.addAction(self.actionHideHFWApp)
        self.menuHFW_application_visibility.addAction(self.actionShowHFWApp)
        self.menuDebug.addAction(self.menuCommander.menuAction())
        self.menuCommander.addAction(self.actionCEMcmd)
        self.menuCommander.addAction(self.actionMLDcmd)
        self.menuCommander.addAction(self.actionFZWcmd)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionOpenOnlineManual)
        self.menuScans.addAction(self.actionScan_control)
        self.retranslateUi(MainWindow)
        self.MainTabWidget.setCurrentIndex(0)
        self.mode.setCurrentIndex(0)
        self.manual_tabWidget.setCurrentIndex(0)
        self.spectroscopy_scan_mode.setCurrentIndex(2)
        self.spectroscopy_sample_rate.setCurrentIndex(0)
        self.display_unit.setCurrentIndex(2)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", "Motorised Cateye Application", None))
        self.actionLoad_configuration.setText(QCoreApplication.translate("MainWindow", "Load configuration file", None))
        self.actionSave_configuration_file.setText(QCoreApplication.translate("MainWindow", "Save configuration file", None))
        self.actionReset.setText(QCoreApplication.translate("MainWindow", "Reset", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", "Close", None))
        self.actionConnectCEM.setText(QCoreApplication.translate("MainWindow", "Motorised Cateye (CEM)", None))
        self.actionConnectMLD.setText(QCoreApplication.translate("MainWindow", "Motorised Laser Driver (MLD)", None))
        self.actionConnectFZW.setText(QCoreApplication.translate("MainWindow", "Fizeau Wavemeter (FZW)", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", "About", None))
        self.actionCEMcmd.setText(QCoreApplication.translate("MainWindow", "CEM", None))
        self.actionMLDcmd.setText(QCoreApplication.translate("MainWindow", "MLD", None))
        self.actionFZWcmd.setText(QCoreApplication.translate("MainWindow", "FZW", None))
        self.actionOpenOnlineManual.setText(QCoreApplication.translate("MainWindow", "Open online manual", None))
        self.actionMLDSettings.setText(QCoreApplication.translate("MainWindow", "Motorised Laser Driver (MLD)", None))
        self.actionScan_control.setText(QCoreApplication.translate("MainWindow", "Scan control", None))
        self.actionReset_CEM_server.setText(QCoreApplication.translate("MainWindow", "Reset CEM server", None))
        self.actionParameters.setText(QCoreApplication.translate("MainWindow", "Parameters", None))
        self.actionHigh_Finesse_Wavemeter_HFW.setText(QCoreApplication.translate("MainWindow", "High Finesse Wavemeter (HFW)", None))
        self.actionConnectHFW.setText(QCoreApplication.translate("MainWindow", "High Finesse Wavemeter (HFW)", None))
        self.actionHideHFWApp.setText(QCoreApplication.translate("MainWindow", "Hide", None))
        self.actionShowHFWApp.setText(QCoreApplication.translate("MainWindow", "Show", None))
        self.manual_laser_settings.setTitle(QCoreApplication.translate("MainWindow", "Laser settings", None))
        self.label_laser_current.setText(QCoreApplication.translate("MainWindow", "Current", None))
        self.btn_current_on_off.setText(QCoreApplication.translate("MainWindow", "OFF", None))
        self.laser_current.setText(QCoreApplication.translate("MainWindow", "150.00 mA", None))
        self.label_laser_temperature.setText(QCoreApplication.translate("MainWindow", "Temperature", None))
        self.btn_tec_on_off.setText(QCoreApplication.translate("MainWindow", "OFF", None))
        self.laser_temperature.setText(QCoreApplication.translate("MainWindow", "24.00 °C", None))
        self.label.setText(QCoreApplication.translate("MainWindow", "Filter angle", None))
        self.btn_home_filter.setText(QCoreApplication.translate("MainWindow", "Home", None))
        self.filter_angle.setText(QCoreApplication.translate("MainWindow", "20.000°", None))
        self.manual_frequency_settings.setTitle(QCoreApplication.translate("MainWindow", "Frequency settings", None))
        self.frequency_error.setText(QCoreApplication.translate("MainWindow", "0000.000 Ghz", None))
        self.label_frequency_error.setText(QCoreApplication.translate("MainWindow", "Frequency error", None))
        self.mode.setItemText(0, QCoreApplication.translate("MainWindow", "Very-fast", None))
        self.mode.setItemText(1, QCoreApplication.translate("MainWindow", "Fast", None))
        self.mode.setItemText(2, QCoreApplication.translate("MainWindow", "Fine", None))
        self.mode.setItemText(3, QCoreApplication.translate("MainWindow", "Very-fine", None))
        self.mode.setItemText(4, QCoreApplication.translate("MainWindow", "Retune", None))
        self.label_mode.setText(QCoreApplication.translate("MainWindow", "Mode", None))
        self.btn_move_to_frequency.setText(QCoreApplication.translate("MainWindow", "Move", None))
        self.btn_move_and_hold.setText(QCoreApplication.translate("MainWindow", "Move and Hold", None))
        self.label_retry_on_error.setText(QCoreApplication.translate("MainWindow", "Retry on error", None))
        self.retry_on_error.setSuffix(QCoreApplication.translate("MainWindow", " x", None))
        self.retry_on_error.setPrefix("")
        self.label_set_frequency.setText(QCoreApplication.translate("MainWindow", "Set frequency", None))
        self.set_frequency.setPrefix("")
        self.set_frequency.setSuffix(QCoreApplication.translate("MainWindow", " THz", None))
        self.label_set_wavelength.setText(QCoreApplication.translate("MainWindow", "Set wavelength", None))
        self.set_wavelength.setPrefix("")
        self.set_wavelength.setSuffix(QCoreApplication.translate("MainWindow", " nm", None))
        self.manual_tabWidget.setTabText(self.manual_tabWidget.indexOf(self.tab_filter_position), QCoreApplication.translate("MainWindow", "Filter position", None))
        self.btn_mode_scan.setText(QCoreApplication.translate("MainWindow", "View snapshot of scan\nScan continues", None))
        self.btn_mode_scan_and_move.setText(QCoreApplication.translate("MainWindow", "Halt at centre of stable mode\nScan halts", None))
        self.btn_mode_scan_resume.setText(QCoreApplication.translate("MainWindow", "Resume scan\n", None))
        self.manual_tabWidget.setTabText(self.manual_tabWidget.indexOf(self.tab_mode_scans), QCoreApplication.translate("MainWindow", "Mode scans", None))
        self.btn_clear_log.setText(QCoreApplication.translate("MainWindow", "Clear", None))
        self.manual_tabWidget.setTabText(self.manual_tabWidget.indexOf(self.tab_time_series), QCoreApplication.translate("MainWindow", "Time-series", None))
        self.manual_tabWidget.setTabText(self.manual_tabWidget.indexOf(self.manual_fzw), QCoreApplication.translate("MainWindow", "Wavemeter", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab_manual), QCoreApplication.translate("MainWindow", "Manual", None))
        self.spectroscopy_laser_settings.setTitle(QCoreApplication.translate("MainWindow", "Laser settings", None))
        self.btn_spectroscopy_start.setText(QCoreApplication.translate("MainWindow", "Start", None))
        self.label_scan_speed.setText(QCoreApplication.translate("MainWindow", "Scan speed", None))
        self.label_sample_rate.setText(QCoreApplication.translate("MainWindow", "Sample rate", None))
        self.label_scan_status.setText(QCoreApplication.translate("MainWindow", "Scan status", None))
        self.scan_status.setText(QCoreApplication.translate("MainWindow", "Ready to start", None))
        self.scan_speed.setText(QCoreApplication.translate("MainWindow", "0.00 GHz/s", None))
        self.sample_rate.setText(QCoreApplication.translate("MainWindow", "0.00 /s", None))
        self.spectroscopy_scan_mode.setItemText(0, QCoreApplication.translate("MainWindow", "Fast", None))
        self.spectroscopy_scan_mode.setItemText(1, QCoreApplication.translate("MainWindow", "Medium", None))
        self.spectroscopy_scan_mode.setItemText(2, QCoreApplication.translate("MainWindow", "Slow", None))
        self.label_scan_mode.setText(QCoreApplication.translate("MainWindow", "Scan mode", None))
        self.label_scan_replicates.setText(QCoreApplication.translate("MainWindow", "Replicates", None))
        self.label_sample_rate_2.setText(QCoreApplication.translate("MainWindow", "Sample rate", None))
        self.spectroscopy_sample_rate.setItemText(0, QCoreApplication.translate("MainWindow", "Fast", None))
        self.spectroscopy_sample_rate.setItemText(1, QCoreApplication.translate("MainWindow", "Slow", None))
        self.max_frequency.setPrefix("")
        self.max_frequency.setSuffix(QCoreApplication.translate("MainWindow", " THz", None))
        self.min_frequency.setPrefix("")
        self.min_frequency.setSuffix(QCoreApplication.translate("MainWindow", " THz", None))
        self.label_min_frequency.setText(QCoreApplication.translate("MainWindow", "Minimum frequency", None))
        self.label_max_frequency.setText(QCoreApplication.translate("MainWindow", "Maximum frequency", None))
        self.btn_scan_n_peaks.setText(QCoreApplication.translate("MainWindow", "Scan n peaks", None))
        self.btn_toggle_resonance.setText(QCoreApplication.translate("MainWindow", "Toggle\nResonance", None))
        self.btn_clear_spectroscopy.setText(QCoreApplication.translate("MainWindow", "Clear", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab_spectroscopy), QCoreApplication.translate("MainWindow", "Spectroscopy", None))
        self.MainTabWidget.setTabText(self.MainTabWidget.indexOf(self.tab_resonance), QCoreApplication.translate("MainWindow", "Resonance", None))
        self.btn_abort.setText(QCoreApplication.translate("MainWindow", "Abort", None))
        self.measured_frequency.setText(QCoreApplication.translate("MainWindow", "385.000000", None))
        self.display_unit.setItemText(0, QCoreApplication.translate("MainWindow", "nm (vac)", None))
        self.display_unit.setItemText(1, QCoreApplication.translate("MainWindow", "nm (air)", None))
        self.display_unit.setItemText(2, QCoreApplication.translate("MainWindow", "THz", None))
        self.display_unit.setItemText(3, QCoreApplication.translate("MainWindow", "cm⁻¹", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", "File", None))
        self.menuDevices.setTitle(QCoreApplication.translate("MainWindow", "Devices", None))
        self.menuConnect.setTitle(QCoreApplication.translate("MainWindow", "Connect", None))
        self.menuAdvanced_settings.setTitle(QCoreApplication.translate("MainWindow", "Advanced settings", None))
        self.menuHFW_application_visibility.setTitle(QCoreApplication.translate("MainWindow", "HFW application visibility", None))
        self.menuDebug.setTitle(QCoreApplication.translate("MainWindow", "Debug", None))
        self.menuCommander.setTitle(QCoreApplication.translate("MainWindow", "Commander", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", "Help", None))
        self.menuScans.setTitle(QCoreApplication.translate("MainWindow", "&Calibration scans", None))

# okay decompiling cem/gui/ui_cem_app.pyc
